In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
county = pd.read_excel('County.xlsx')
vax = pd.read_excel('vax.xlsx')
cases = pd.read_excel('cases.xlsx')

In [15]:
vax

      Record_Date county_Name  partially_Vaxed  fully_Vaxed  additional_Dose
0      01/01/2021       Adams              3.0          NaN              NaN
1      01/02/2021       Adams            105.0          NaN              NaN
2      01/03/2021       Adams              9.0          NaN              NaN
3      01/04/2021       Adams             80.0          8.0              NaN
4      01/05/2021       Adams             33.0          2.0              NaN
...           ...         ...              ...          ...              ...
22717  12/27/2020        York             36.0          NaN              NaN
22718  12/28/2020        York            520.0          NaN              NaN
22719  12/29/2020        York            565.0          NaN              NaN
22720  12/30/2020        York            515.0          NaN              NaN
22721  12/31/2020        York            253.0          NaN              NaN

[22722 rows x 5 columns]